### ISSUE TITLE
Need a tutorial

### ISSUE THREAD

**Issue by zyh4482** [molgenis/capice#126]
Thanks for your wonderful tool. 

I've been trying to understand how to use capice to predict pathonicity of indels. I have two questions. 

1. I don't know how to get a golden standard training dataset. How could I get/generate pickled model and json files? How to use your model as described in the article to predict my own dataset (genome version: GRCh38)? 

2. I'm working on GRCh38 genome. When using the online service https://capice.molgeniscloud.org/ , I found some exonic coordinates were labeld as intergenic or intronic. Does the website take GRCh37 as reference? 

Thank you so much.

**Comment by zyh4482** [comment]
I found a pickled model here: https://github.com/molgenis/capice/releases/download/v3.0.0/v3.0.0-v1_grch38.pickle.dat

Is it the one I'm supposed to use? 

After running `predict` step using above file, I filtered duplicated indels and kept the largest score for each mutation. I found all indels have score > 0.02. Is there a way to determine the threshold of a pathogenic indel?

**Comment by SietsmaRJ** [comment]
Hello, thank you for your interest in CAPICE. I apologize for the late response.

As for your first question, CAPICE on the web-based https://capice.molgeniscloud.org/ is still based on CAPICE v1.1, which is heavily outdated by now and we have plans to update that in the future. I highly suggest using either a clone of this repository with the latest version, using the [pypi](https://pypi.org/project/capice/) version or using the [singularity](https://download.molgeniscloud.org/downloads/vip/images/) image of CAPICE v3.2.0. It is correct that the files generated by the web-based version are still only supported for GRCh37.

As for the training dataset: we're heavily in favor of FAIR (Findable, Accessible, Interoperable, Reusable) data, but we still want to keep an edge over the competition. The steps to reproduce a new training dataset are described in the [CAPICE paper](https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-020-00775-w).

The pickled model that you have found is correct yes. This model performs slightly worse than the model described in the CAPICE paper, but this is due to a difference in feature selection.

As for thresholds, this is something that we are still investigating. On one side, you need thresholds to determine what variants are and what variants are not interesting to take a further look at, but on the other side that is not where CAPICE strength is at. CAPICE strength is to provide you with scores, high means the variant is very likely pathogenic and thus interesting to look at in further detail. The lower the score, the less interesting the variant becomes. We have plans to include some form of thresholds, as currently the output column "suggested_class" is only filled with "VUS", but in the future we would like to add "damaging" and "neutral" or something similar to this output column, based on findings per gene. This means that currently I'm not able to supply you with a threshold.

Again sorry for the late response, if you have any further question feel free to ask.

**Comment by zyh4482** [comment]
Your answer is very helpful. Thank you so much.
